export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_RESOLVE = 'REQUEST_ROBOTS_RESOLVE';
export const REQUEST_ROBOTS_REJECT = 'REQUEST_ROBOTS_REJECT';
